@startuml
class DeleteObjectCommand {
    + <<override>> Execute() : void
    + <<override>> Undo() : void
    + <<override>> Redo() : void
    + <<override>> ClearFirstUndo() : void
    + <<override>> ClearRedo() : void
}
class "Stack`1"<T> {
}
class "LinkedList`1"<T> {
}
BaseObjectCommands <|-- DeleteObjectCommand
DeleteObjectCommand --> "redoStack<SceneObject[]>" "Stack`1"
DeleteObjectCommand --> "undoLinkedList<SceneObject[]>" "LinkedList`1"
@enduml
