@startuml
class DeselectObjectCommand {
    + <<override>> Execute() : void
    + <<override>> Undo() : void
    + <<override>> Redo() : void
    + <<override>> ClearFirstUndo() : void
    + <<override>> ClearRedo() : void
    + InitializePreDeselected(preDeselected:List<SceneObject>) : void
}
class "LinkedList`1"<T> {
}
class "Stack`1"<T> {
}
class "List`1"<T> {
}
BaseEditorCommand <|-- DeselectObjectCommand
DeselectObjectCommand --> "undoLinkedList<SceneObject[]>" "LinkedList`1"
DeselectObjectCommand --> "redoStack<SceneObject[]>" "Stack`1"
DeselectObjectCommand --> "preDeselected<SceneObject>" "List`1"
@enduml
